name: Build and release
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                curl -fsSL https://bun.sh/install | bash
            - name: Install node deps
              run: ~/.bin/bin/bun install
            - name: Build
              run: ~/.bin/bin/bun build.ts , build
            - uses: actions/upload-artifact@v4
              with:
                name: general.css
                path: devel.css