name: Build and release
on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Install dependencies
              run: |
                curl -fsSL https://bun.sh/install | bash
            - name: Install node deps
              run: ~/.bun/bin/bun install
            - name: Build
              run: ~/.bun/bin/bun build.ts , build
            - uses: actions/upload-artifact@v4
              with:
                name: styles
                path: out
            - name: Copy for pages
              run: cp devel.css out/general.css
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                path: out
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4